server:
  port: 8080

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://34.133.191.110:3306/areciboai
    username: root
    password: Arecibo2025!
    druid:
      initial-size: 5
      max-active: 1000
      max-wait: 3000
      min-idle: 5
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      filters: stat,wall,log4j
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

  mail:
    host: smtp.office365.com
    port: 587
    username: team@arecibo.ai
    password: Arecib0!2025
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

logging:
  level:
    ai.arecibo.areciboweb: DEBUG
    org.springframework.web: DEBUG 