spring:
  datasource:
    url: jdbc:mysql://localhost:3306/arecibo_web?useSSL=false&serverTimezone=UTC
    username: arecibo_user
    password: YOUR_SECURE_PASSWORD
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_APP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

logging:
  level:
    ai.arecibo.areciboweb: DEBUG
